import os
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.image import MIMEImage
from typing import Dict


def _html_body(summary: str, date_range: str) -> str:
    # Preserve line breaks from the AI summary
    summary_html = summary.replace("\n", "<br>")
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>HSE Observation Report</title>
  <style>
    body {{ margin: 0; padding: 0; background: #f0f2f5; font-family: Arial, sans-serif; }}
    .wrapper {{ max-width: 820px; margin: 24px auto; background: #ffffff;
                border-radius: 10px; overflow: hidden; box-shadow: 0 2px 12px rgba(0,0,0,.15); }}
    .header {{ background: #1a237e; color: #fff; padding: 28px 36px; }}
    .header h1 {{ margin: 0 0 6px; font-size: 22px; font-weight: 700; }}
    .header p {{ margin: 0; font-size: 13px; opacity: .8; }}
    .body {{ padding: 32px 36px; }}
    .section-title {{ font-size: 11px; font-weight: 700; text-transform: uppercase;
                      letter-spacing: 1px; color: #1a237e; margin: 0 0 10px; }}
    .summary-box {{ background: #f5f7ff; border-left: 4px solid #1a237e;
                    border-radius: 4px; padding: 20px 24px; margin-bottom: 36px; }}
    .summary-box p {{ margin: 0; line-height: 1.75; color: #333; font-size: 14px; }}
    .charts-grid {{ display: grid; grid-template-columns: 1fr 1fr; gap: 20px; }}
    .chart-card {{ border: 1px solid #e8eaf0; border-radius: 8px; overflow: hidden; }}
    .chart-card .chart-label {{ background: #f5f7ff; padding: 10px 14px;
                                font-size: 11px; font-weight: 700;
                                text-transform: uppercase; letter-spacing: 0.8px;
                                color: #1a237e; border-bottom: 1px solid #e8eaf0; }}
    .chart-card img {{ width: 100%; display: block; }}
    .footer {{ background: #f5f5f5; padding: 16px 36px;
               font-size: 11px; color: #999; text-align: center;
               border-top: 1px solid #e0e0e0; }}
  </style>
</head>
<body>
  <div class="wrapper">
    <div class="header">
      <h1>HSE Observation Report</h1>
      <p>Reporting Period: {date_range} &nbsp;&bull;&nbsp; Generated by HSE Reporting System</p>
    </div>
    <div class="body">
      <p class="section-title">Executive Summary</p>
      <div class="summary-box">
        <p>{summary_html}</p>
      </div>

      <p class="section-title">Observation Charts</p>
      <div class="charts-grid">
        <div class="chart-card">
          <div class="chart-label">Observations by Facility</div>
          <img src="cid:chart_facility" alt="Observations by Facility">
        </div>
        <div class="chart-card">
          <div class="chart-label">Observations by Category</div>
          <img src="cid:chart_category" alt="Observations by Category">
        </div>
        <div class="chart-card">
          <div class="chart-label">At-Risk vs Safe</div>
          <img src="cid:chart_saferisk" alt="At-Risk vs Safe">
        </div>
        <div class="chart-card">
          <div class="chart-label">Top At-Risk Categories</div>
          <img src="cid:chart_atrisk" alt="Top At-Risk Categories">
        </div>
      </div>

      <div class="chart-card" style="margin-top: 20px;">
        <div class="chart-label">Interventions by Facility</div>
        <img src="cid:chart_interventions" alt="Interventions by Facility" style="width:100%;display:block;">
      </div>
    </div>
    <div class="footer">
      This report was automatically generated &mdash; please do not reply to this email.
    </div>
  </div>
</body>
</html>"""


def send_email(
    to_email: str,
    subject: str,
    summary: str,
    date_range: str,
    chart_images: Dict[str, bytes],
) -> None:
    """
    Build and send an HTML email with 4 inline chart images.

    MIME structure:
      MIMEMultipart("mixed")
        └── MIMEMultipart("related")
              ├── MIMEText(html)
              ├── MIMEImage(chart_facility)
              ├── MIMEImage(chart_category)
              ├── MIMEImage(chart_saferisk)
              └── MIMEImage(chart_atrisk)
    """
    from_addr = os.environ["SMTP_FROM"]

    msg = MIMEMultipart("mixed")
    msg["From"] = from_addr
    msg["To"] = to_email
    msg["Subject"] = subject

    related = MIMEMultipart("related")

    html_part = MIMEText(_html_body(summary, date_range), "html", "utf-8")
    related.attach(html_part)

    for cid_name, img_bytes in chart_images.items():
        img = MIMEImage(img_bytes, _subtype="png")
        img.add_header("Content-ID", f"<{cid_name}>")
        img.add_header("Content-Disposition", "inline", filename=f"{cid_name}.png")
        related.attach(img)

    msg.attach(related)

    smtp_host = os.environ["SMTP_HOST"]
    smtp_port = int(os.environ.get("SMTP_PORT", "587"))
    smtp_user = os.environ["SMTP_USER"]
    smtp_pass = os.environ["SMTP_PASSWORD"]

    with smtplib.SMTP(smtp_host, smtp_port) as server:
        server.ehlo()
        server.starttls()
        server.ehlo()
        server.login(smtp_user, smtp_pass)
        server.sendmail(from_addr, [to_email], msg.as_string())
